name: social_media_app
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  flutter_lints: ^4.0.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  easy_localization: ^3.0.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/avatar.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/image/
