// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8R8bnD7jjjqBBqxNtFlb7gwrOgJaje8A',
    appId: '1:497427051791:web:16d40a03646344fce27a7a',
    messagingSenderId: '497427051791',
    projectId: 'socialmediaapp-24da5',
    authDomain: 'socialmediaapp-24da5.firebaseapp.com',
    storageBucket: 'socialmediaapp-24da5.appspot.com',
    measurementId: 'G-6FGWETJL02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJpQ5LwEA2GpzqnwC8x3yvsRARNwwXKYg',
    appId: '1:497427051791:android:d44915bacdaec3b2e27a7a',
    messagingSenderId: '497427051791',
    projectId: 'socialmediaapp-24da5',
    storageBucket: 'socialmediaapp-24da5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNYcD7DT6l1vBCASaYMs9PauJBy5cMcg',
    appId: '1:497427051791:ios:8f44903447acbfe3e27a7a',
    messagingSenderId: '497427051791',
    projectId: 'socialmediaapp-24da5',
    storageBucket: 'socialmediaapp-24da5.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNYcD7DT6l1vBCASaYMs9PauJBy5cMcg',
    appId: '1:497427051791:ios:8f44903447acbfe3e27a7a',
    messagingSenderId: '497427051791',
    projectId: 'socialmediaapp-24da5',
    storageBucket: 'socialmediaapp-24da5.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8R8bnD7jjjqBBqxNtFlb7gwrOgJaje8A',
    appId: '1:497427051791:web:33442fa61fe2c71ae27a7a',
    messagingSenderId: '497427051791',
    projectId: 'socialmediaapp-24da5',
    authDomain: 'socialmediaapp-24da5.firebaseapp.com',
    storageBucket: 'socialmediaapp-24da5.appspot.com',
    measurementId: 'G-5GQ1KQB2C5',
  );
}
