// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgx3bogZUP66DPgBDe8IhTYzrpur_RgfI',
    appId: '1:247070538086:web:873a80e06c431a8821f0a7',
    messagingSenderId: '247070538086',
    projectId: 'socialmedia-3f4f1',
    authDomain: 'socialmedia-3f4f1.firebaseapp.com',
    storageBucket: 'socialmedia-3f4f1.appspot.com',
    measurementId: 'G-R69VXT9M1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyideR2VrkLYJ39m5HpeAHZvS4eC_r9_M',
    appId: '1:247070538086:android:7d66ede751643ce421f0a7',
    messagingSenderId: '247070538086',
    projectId: 'socialmedia-3f4f1',
    storageBucket: 'socialmedia-3f4f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoO-PyxwKMpUn2ZZRv0X5jTraiUyW8Aq8',
    appId: '1:247070538086:ios:9955e27fc67077b521f0a7',
    messagingSenderId: '247070538086',
    projectId: 'socialmedia-3f4f1',
    storageBucket: 'socialmedia-3f4f1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoO-PyxwKMpUn2ZZRv0X5jTraiUyW8Aq8',
    appId: '1:247070538086:ios:9955e27fc67077b521f0a7',
    messagingSenderId: '247070538086',
    projectId: 'socialmedia-3f4f1',
    storageBucket: 'socialmedia-3f4f1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgx3bogZUP66DPgBDe8IhTYzrpur_RgfI',
    appId: '1:247070538086:web:7faee229bac1807a21f0a7',
    messagingSenderId: '247070538086',
    projectId: 'socialmedia-3f4f1',
    authDomain: 'socialmedia-3f4f1.firebaseapp.com',
    storageBucket: 'socialmedia-3f4f1.appspot.com',
    measurementId: 'G-Q83NLFLZ8R',
  );

}